"""add_title_and_era_fields

Revision ID: 2fa26a706ea6
Revises: a8bb96c18f0c
Create Date: 2025-11-23 17:58:50.486382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa26a706ea6'
down_revision = 'a8bb96c18f0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('figure', sa.Column('title', sa.String(length=256), nullable=True))
    op.add_column('figure', sa.Column('era', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('figure', 'era')
    op.drop_column('figure', 'title')
    # ### end Alembic commands ###
