"""add_figure_fields

Revision ID: a8bb96c18f0c
Revises: b53d39a345e5
Create Date: 2025-11-23 17:33:38.952492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8bb96c18f0c'
down_revision = 'b53d39a345e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('figure', sa.Column('introduction', sa.Text(), nullable=True))
    op.add_column('figure', sa.Column('biography', sa.Text(), nullable=True))
    op.add_column('figure', sa.Column('contributions', sa.Text(), nullable=True))
    op.add_column('figure', sa.Column('image_intro', sa.String(length=256), nullable=True))
    op.add_column('figure', sa.Column('image_activity', sa.String(length=256), nullable=True))
    op.add_column('figure', sa.Column('image_ext_1', sa.String(length=256), nullable=True))
    op.add_column('figure', sa.Column('image_ext_2', sa.String(length=256), nullable=True))
    op.add_column('figure', sa.Column('video_1', sa.String(length=256), nullable=True))
    op.add_column('figure', sa.Column('video_2', sa.String(length=256), nullable=True))
    op.drop_column('figure', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('figure', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('figure', 'video_2')
    op.drop_column('figure', 'video_1')
    op.drop_column('figure', 'image_ext_2')
    op.drop_column('figure', 'image_ext_1')
    op.drop_column('figure', 'image_activity')
    op.drop_column('figure', 'image_intro')
    op.drop_column('figure', 'contributions')
    op.drop_column('figure', 'biography')
    op.drop_column('figure', 'introduction')
    # ### end Alembic commands ###
